
# root bitnami

version: '2'
services:
  apache_php:
    image: php:8-apache
    volumes:
      - ./src/:/var/www/html
    expose:
    - 80
    ports:
      - 80:80
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '8080:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local

